multiTenant: false
admin_password: repl_passowrd
image:
  repository: registry.gitlab.com/cmc_system/cmc
  tag: latest
webDeployment:
  secretKeyBase: 5d1ee3590cdac32f527d1c4c835578859ecbd50ac1b03ff6d4689c19d732b5c9050ceb66d8b625cacadb1c1228095a7fd855933ce1881075a577e7cb8aea3432
  sentryDsn:
  enviroment: production
postgresql:
  postgresqlUsername: postgres
  postgresqlDatabase: database
  postgresqlPassword: repl_password
redis:
  usePassword: false
  cluster:
    enabled: false

installJobDelay: 5
databasePersistence:
  storageClassName:
webPersistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi
  # storageClassName:
webAws:
  enabled: false
  key:
  secret:
  region:
  endpoint:
  directory:
databaseService:
  externalIp:
ingress:
  enabled: false
  # annotations:
  #   certmanager.k8s.io/cluster-issuer:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  # tls:
  #   - secretName: chart-example-tls
  #     hosts:
  #     - chart-example.local
mailer:
  createSecret: true
  smtp_domain: ""
  domain: ""
  user_name: ""
  password: ""
  port: ""
payment:
  enabled: false
  host: https://example.com

google:
  webHook: "false"
  clientId: ""
  calenderSecret: ""
deviseHeaderJs: ""
administrationHeaderJs: ""
