multiTenant: true
installJobDelay: 60
url: ticktensio.com
deprecatedUrl: cost-manager.com
postgresql:
  master:
    podAnnotations:
      backup.velero.io/backup-volumes: data
  resources:
    requests:
      memory: 0Mi
      memory: 200Mi
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host ~ ^(.*)cost-manager\.com$) {
        return 301 https://$1ticktensio.com$request_uri;
      }
      if ($host ~ ^www.(.*)ticktensio\.com$) {
        return 301 https://$1ticktensio.com$request_uri;
      }
  tls:
    - secretName: cost-manager-tls
      hosts:
        - "*.cost-manager.com"
        - "cost-manager.com"
        - "*.ticktensio.com"
        - "ticktensio.com"
webAws:
  enabled: true
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  directory: webcloudpower/cmc-production

payment:
  enabled: true
  host: https://payment.ticktensio.com
  stripePublicKey: pk_live_Dq4ZzdS1gJgbm13XcdqmFvMH00NaWk8hVd

mailer:
  smtp_domain: smtp.migadu.com 
  domain: ticktensio.com 
  user_name: info@ticktensio.com
  port: "587"
  password: ""

google:
  webHook: "true"

deviseHeaderJs: |
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127775143-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-127775143-2');
  </script>
administrationHeaderJs:
  <script>
    window.googleAnalyticsId = 'UA-127775143-2'
  </script>

reCaptcha:
  enabled: true
